import { Fragment } from "react";
import { useLanguage } from "../hooks/useLanguage";
import Section from "./ui/Section";

const events = {
  pt: [["Jul. 2026", "Fui efetivado na Inside Sistemas para trabalhar com desenvolvimento de inteligência artificial e dados, criando automações, agentes e dashboards para apoiar processos e decisões."], ["Fev. 2026", "Iniciei minha trajetória na Inside Sistemas no suporte técnico, aprofundando meu conhecimento sobre ERP, regras de negócio e necessidades dos usuários."], ["Mar. 2025", "Retornei à engenharia de computação na UTFPR com objetivos profissionais mais claros e foco em integrar teoria, prática e evolução constante."], ["Mar. 2024", "Atuei na seção de informática do Exército Brasileiro. A experiência fortaleceu minha disciplina, resiliência e atuação sob pressão."], ["Mar. 2023", "Ingressei em engenharia de computação na UTFPR e comecei meus estudos em programação pelo front-end, consolidando minha base técnica."]],
  en: [["Jul. 2026", "I was hired by Inside Sistemas as an AI and data analyst, building automations, agents, and dashboards to support processes and decision-making."], ["Feb. 2026", "I joined Inside Sistemas in technical support, deepening my understanding of ERP systems, business rules, and user needs."], ["Mar. 2025", "I returned to computer engineering at UTFPR with clearer professional goals and a focus on combining theory, practice, and continuous growth."], ["Mar. 2024", "I worked in the Brazilian Army IT department. The experience strengthened my discipline, resilience, and ability to perform under pressure."], ["Mar. 2023", "I started computer engineering at UTFPR and began studying programming through front-end development, building my technical foundation."]],
};
function AboutMe() {
  const { lang } = useLanguage();
  return <Section id="sobre-mim" title={lang === "pt" ? "Sobre mim" : "About me"} index="05"><div className="grid grid-cols-[68px_26px_minmax(0,1fr)] gap-x-3 md:grid-cols-[92px_26px_minmax(0,1fr)] md:gap-x-5">{events[lang].map(([date, text], index) => { const first = index === 0; const last = index === events[lang].length - 1; return <Fragment key={date}><div className="pb-[30px] pt-6 text-right font-mono text-[13px] font-semibold tracking-[.1em] text-accentSoft">{date}</div><div className="relative flex justify-center"><span className="absolute w-px bg-lineStrong" style={{ top: first ? "31px" : 0, bottom: last ? "auto" : 0, height: last ? "31px" : "auto" }} /><span className="relative mt-[26px] h-[11px] w-[11px] rounded-full border-2 border-accent" style={{ background: first ? "var(--accent)" : "var(--bg)", boxShadow: "0 0 0 5px var(--accent-bg)" }} /></div><p className="max-w-[74ch] pb-[30px] pt-5 text-[14.5px] leading-[1.8] text-muted">{text}</p></Fragment>; })}</div></Section>;
}
export default AboutMe;
